import csv

kan_primer = 'GCATTGAGCTAGTCAGTGAG'
#primer sequence between upstream and barcode
kan_cassette = 'TTAATTAAATGGCGATAGCTAGACTGGGCGGTTTTATGGACAGCAAGCGAACCGGAATTGCCAGCTGGGGCGCCCTCTGGTAAGGTTGGGAAGCCCTGCAAAGTAAACTGGATGGCTTTCTTGCCGCCAAGGATCTGATGGCGCAGGGGATCAAATCTGATCAAGAGACAGGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTCCAAGACGAGGCAGCGCGGCTATCGTGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGGCGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGCGGCTGCATACGCTTGATCCGGCTACCTGCCCATTCGACCACCAAGCGAAACATCGCATCGAGCGAGCACGTACTCGGATGGAAGCCGGTCTTGTCGATCAGGATGATCTGGACGAAGAGCATCAGGGGCTCGCGCCAGCCGAACTGTTCGCCAGGCTCAAGGCGCGGATGCCCGACGGCGAGGATCTCGTCGTGACCCATGGCGATGCCTGCTTGCCGAATATCATGGTGGAAAATGGCCGCTTTTCTGGATTCATCGACTGTGGCCGGCTGGGTGTGGCGGACCGCTATCAGGACATAGCGTTGGCTACCCGTGATATTGCTGAAGAGCTTGGCGGCGAATGGGCTGACCGCTTCCTCGTGCTTTACGGTATCGCCGCTCCCGATTCGCAGCGCATCGCCTTCTATCGCCTTCTTGACGAGTTCTTCTGATTCAGACGGCATGCGGCCGC'
# includeskan cassette (Pac1 +promoter+kanr+Dus+Not1)


with open('MS11Reverse_UpDownSeq.csv', 'r') as MS11Reverse_updown:
    with open('MS11RevFullConstructSeq.csv', 'w', newline='') as MS11Rev_full:
        writer = csv.writer(MS11Rev_full)
        reader = csv.reader(MS11Reverse_updown)

        # header row in output file
        header_row = next(reader)
        header_row.append('fullconstruct')
        writer.writerow(header_row)

        #loop through to get the start and stop
        for row in reader:
            up = row[6]
            down = row[7]
            barcode = row[8]
            fullconstruct = up + kan_primer + barcode + kan_cassette + down
            row.append(fullconstruct)
            writer.writerow(row)
